name: CI
on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  beta-deploy:
    name: Beta Deploy
    timeout-minutes: 15
    runs-on: ubuntu-latest
    environment: beta

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: us-west-2

      - name: Build project
        run: pnpm --filter web build

      - name: Deploy CDK stack
        run: pnpm --filter=@ericfinance/cdk run deploy --context stage=beta
