name: PR Check

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-lint:
    name: Build & Lint
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Setup Node.js environment
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Lint web application
        run: pnpm --filter web lint

      - name: Build web application
        run: pnpm --filter web build

      - name: Test CDK package
        run: pnpm --filter @ericfinance/cdk run test

      - name: Synthesize CDK stacks
        run: pnpm --filter @ericfinance/cdk run synth
